// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
)

type Game struct {
	ID     int64
	Answer sql.NullString
}

type Guess struct {
	ID     int64
	GameID sql.NullInt64
	Guess  sql.NullString
}
